services: 
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: postgres
      POSTGRES_USER: umg_test
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U umg_test -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    command: sh -c "npm install && npm run start"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    expose:
      - 8001
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://umg_test:test@db:5432/postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=umg_test
      - DB_PASSWORD=test
      - DB_DATABASE=postgres
    volumes:
      - ./week-8:/week-8
      - /week-8/node_modules
  

      